spring.datasource.url=jdbc:postgresql://localhost:5432/cyber_asset_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

gemini.api.key=${GEMINI_API_KEY}